### PR TITLE
Release/0.36.4

### PR DESCRIPTION
**Pull request by rquinio**
I've merged vanilla modified files with patch 2.4.2.
Also updated ValidatorSettings to latest version of validator.

### CODE REVIEW

**Comment by xirsoi** [comment]
Lets wait for 2.4.3 to drop before we merge and release

**Comment by xirsoi** [comment]
Also, there are a couple of bugs that could/should be squashed while we're at it.

**Comment by xirsoi** [comment]
woo! that was a big one. I suspect many of the changes i just merged were from previous versions.
Unless PI just did a crazy amount of changes to the realm decisions!

**Comment by rquinio** [comment]
Did you do a 2 way-merge or 3-way merge ? I think you've overwritten some ACR changes, hence the big changes :)

**Pull request merged**
