### PR TITLE
Feature/29 gaulish culture

### PR DESCRIPTION
**Pull request by xirsoi**
Quick version of Gaulish culture with heavy cav retinue and building.
We have to include 00_cultures.txt now, but we'll be adding Coptic in the future, so this would be necessary anyway.

Also includes unrelated bug fix for the 'Adopt Feudalism' and 'Adopt Republicanism' decisions.

### CODE REVIEW

**Comment by rquinio** [comment]
Is it possible to add only the new culture rather than whole 00_cultures.txt, like it's done for religions ?

**Comment by schwarherz** [comment]
yes, simply name the new file chronologically after 00_cultures.txt
(perhaps even 01_ancient_cultures.txt) in the same folder and format it the
same as the 00_cultures.txt with the new information.

**Comment by xirsoi** [comment]
Ah, that stupid thing again. I'll do just that so we don't have to have the whole thing.

**Comment by xirsoi** [comment]
That creates a second "Celtic" group in the culture selection menu in Ruler Designer.
I don't like that very much. Anymore input?

**Comment by schwarherz** [comment]
Well, you can't overwrite an old group in a new file, unfortunately. Nothing says you can't use a new culture group "reconstructed celtic" or something like that. Other than that you would pretty much HAVE to use 00_cultures.txt

**Comment by xirsoi** [comment]
Well then, I guess we'll just have to include 00_cultures.txt

**Comment by rquinio** [comment]
Too bad :/

Is there an encoding issue in 00_cultures.txt ? My editor doesn't display characters properly .
Also might need to add # Audax Validator "!" Ignore_NEXT due to duplicate names in lists (there doesn't seem to be an option to disable in ValidatorSettings.txt)

**Comment by schwarherz** [comment]
Be sure you're encoding and viewing the document in ANSI instead of UTF-8. CK2 uses ANSI for its character encoding, if you're viewing or writing in UTF-8 it'll display wrong.

**Comment by xirsoi** [comment]
I'm using SublimeText3, and it might be defaulting to UTF-8. I'll make sure to take care of this and push it up.

**Comment by xirsoi** [comment]
So, when you say "ANSI", do you mean Windows-1251, or do you mean ASCII-7?

**Comment by rquinio** [comment]
I confirm that fixed it. Good to merge !

**Comment by xirsoi** [comment]
Woot!

**Comment by rquinio** [comment]
It's not merged :p

**Pull request merged**
